# Generated by Django 2.1.7 on 2019-04-07 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField(max_length=500)),
            ],
            options={
                'db_table': 'comments',
                'ordering': ('-modified',),
            },
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('english_name', models.CharField(blank=True, max_length=255, null=True)),
                ('chinese_name', models.CharField(max_length=255, unique=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('web_site', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=255, null=True)),
                ('introduction', models.TextField(blank=True, max_length=255, null=True)),
                ('hours', models.CharField(blank=True, max_length=255, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('quadrant', models.CharField(blank=True, max_length=255, null=True)),
                ('slug', models.SlugField(editable=False, unique=True)),
            ],
            options={
                'db_table': 'restaurants',
                'ordering': ('id',),
            },
        ),
    ]
