# Generated by Django 2.1.2 on 2018-10-09 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('english_name', models.CharField(max_length=50, unique=True)),
                ('chinese_name', models.CharField(max_length=100, unique=True)),
                ('address', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=20)),
                ('introduction', models.CharField(max_length=255)),
                ('hours', models.CharField(blank=True, max_length=255, null=True)),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
                ('quadrant', models.CharField(max_length=10)),
            ],
        ),
    ]
