# Generated by Django 2.1.7 on 2019-04-16 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='address',
            field=models.CharField(blank=True, default='Calgary', max_length=255),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='city',
            field=models.CharField(blank=True, default='Calgary', max_length=255),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='english_name',
            field=models.CharField(blank=True, default='Unknown', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='hours',
            field=models.CharField(blank=True, default='Unknown', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='introduction',
            field=models.TextField(blank=True, default='Unknown', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='phone',
            field=models.CharField(blank=True, default='Unknown', max_length=255),
            preserve_default=False,
        ),
    ]
