# Generated by Django 2.1.2 on 2018-10-09 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basics', '0002_auto_20181009_0257'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='city',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='web_site',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='id',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False),
        ),
        migrations.AlterModelTable(
            name='restaurant',
            table='restaurants',
        ),
    ]
