# Generated by Django 2.1.2 on 2018-10-10 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basics', '0003_auto_20181009_0318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='english_name',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
