# Generated by Django 2.1.2 on 2018-10-10 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basics', '0004_auto_20181010_0031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='english_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
