# Generated by Django 2.1.2 on 2018-10-10 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basics', '0005_auto_20181010_0035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='chinese_name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='city',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='english_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='phone',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='quadrant',
            field=models.CharField(max_length=255),
        ),
    ]
