# Generated by Django 2.1.2 on 2018-10-14 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basics', '0010_auto_20181013_1629'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='restaurant',
            options={'ordering': ('id',)},
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='quadrant',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
