# Generated by Django 2.1.2 on 2018-10-14 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basics', '0011_auto_20181014_0456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
