# Generated by Django 2.1.2 on 2018-10-15 21:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basics', '0013_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='restaurant',
            field=models.ForeignKey(db_column='restaurant', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='basics.Restaurant', to_field='chinese_name'),
        ),
    ]
